- name: loops in ansible
  hosts: local
  connection: local
  tasks:
    - name: loops in ansible
      loop:
        - Neethika
        - Shynu
        - Kushi
      ansible.builtin.debug:
        msg: "{{ item }}"

    - name: loops with key value pairs
      loop:
      - { firstname: 'Neethika', lastname: 'Shynu', DOB: '06-04-1998'}
      - { firstname: 'kushi', lastname: 'pranavi', DOB: '28-02-2024'}
      ansible.builtin.debug:
        msg: "{{ item.firstname }}, {{ item.lastname }}, {{ item.DOB }}"

    - name: loops by ref the file 
      loop:
        - loop_vars.yaml
      ansible.builtin.debug:
        msg: "{{ item.firstname }}, {{ item.lastname }}, {{ item.dob }}"