- name: loops in ansible
  hosts: local
  connection: local
  vars_files:
    - loop_vars.yaml
  tasks:
    - name: loops in ansible
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop:
        - Neethika
        - Shynu
        - Kushi

    - name: loops with key value pairs
      ansible.builtin.debug:
        msg: "{{ item.firstname }}, {{ item.lastname }}, {{ item.DOB }}"
      loop:
      - { firstname: 'Neethika', lastname: 'Shynu', DOB: '06-04-1998'}
      - { firstname: 'kushi', lastname: 'pranavi', DOB: '28-02-2024'}

    - name: loops by ref the file 
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ user }}"