- name: Play1
  hosts: local
  connection: local
  tasks:
  - name: This is Task1
    ansible.builtin.debug:
      msg: "Hi I am play1 task1"

  - name: This is Task2
    ansible.builtin.debug:
      msg: ="This is Task2 from Play1"

- name: play2
  hosts: local
  connection: local
  tasks:
    - name: This is Task1
      ansible.builtin.debug:
        msg: "This is Task1 of Play2"

    - name: This is Task2
      ansible.builtin.debug:
        msg: "This is Task2 of Play2"

- name: Play3
  hosts: local
  connection: local
  tasks:
    - name: This is Task1
      ansible.builtin.debug:
        msg: "This is Task1 of Play3"
    
    - name: This is Task2
      ansible.builtin.debug:
        msg: "This is Task2 of Play3"