- name: Varaiables that is mentioned in the play
  hosts: local
  connection: local
  #vars: --> 5th pref
  #  WELCOME_MESSAGE: "HOLA!!WELCOME TO PLAY/GLOBAL VARIABLE"
  #vars_prompt: -->4th pref
  #  - name: WELCOME_MESSAGE
  #    prompt: Please enter welcome WELCOME_MESSAGE
  #vars_files: --> 3rd pref
  #  - course.yaml
  tasks:
    - name: Varaible preference test
      #vars: --> 2nd preference
      #  WELCOME_MESSAGE: "HOLA!!WELCOME TO TAKS/LOCAL VARIABLE"
      ansible.builtin.debug:
        msg: "{{ WELCOME_MESSAGE }}"
