- name: Varaiables that is mentioned in the play
  hosts: local
  connection: local
  vars:
    WELCOME_MESSAGE: "HOLA!!WELCOME TO PLAY/GLOBAL VARIABLE"
  vars_prompt:
    - name: WELCOME_MESSAGE
      prompt: Please enter welcome WELCOME_MESSAGE
  vars_files:
    - course.yaml
  tasks:
    - name: Varaible preference test
      #vars: --> 2nd preference
      #  WELCOME_MESSAGE: "HOLA!!WELCOME TO TAKS/LOCAL VARIABLE"
      ansible.builtin.debug:
        msg: "{{ WELCOME_MESSAGE }}"
