- name: Using variable stored in a file
  hosts: local
  connection: local
  vars_files:
    - course.yaml
  tasks:
    - name: Print course information
      ansible.builtin.debug:
        msg: "The name of the course is {{ COURSE }} and the duration is {{ DURATION }} and the learner is {{ LEARNER }}"
